### ISSUE TITLE
No status update for entities or MQTT

### ISSUE THREAD

**Issue by mrwee** [dchesterton/texecom2mqtt-hassio#12]
After the recent trouble and update of the Texecom integration, I get an initial status update for zones, but then they don't change. I'm unsure where the problem actually lies :(
Hass claims I'm on  1.0.18 of the integration.
Core: 2021.2.2
Supervisor: 2021.02.6

My config:
```
texecom:
  host: 192.168.1.xx
  udl_password: 'xxxx'
mqtt:
  host: 'mqtt://fqdn:1883'
  username: USERNAME
  password: PASSWORD
  client_id: texecom2mqtt
  keepalive: 30
  retain: true
homeassistant:
  discovery: true
areas:
  - id: A
    full_arm: armed_away
    part_arm_1: armed_home
zones: []
log: debug
```

Supervisor log:
```
21-02-11 14:31:14 WARNING (MainThread) [supervisor.misc.tasks] Watchdog found a problem with c15a2434_texecom2mqtt!
21-02-11 14:31:14 INFO (SyncWorker_1) [supervisor.docker.interface] Cleaning addon_c15a2434_texecom2mqtt application
21-02-11 14:31:14 INFO (SyncWorker_1) [supervisor.docker.addon] Starting Docker add-on dchesterton/texecom2mqtt with version None
```
I see the Texecom log filling up with lots of status information, it just seems like neither Hass nor MQTT get's updated.

Any ideas?

**Comment by dchesterton** [comment]
Nothing looks untoward with your config. Can you post the full debug log for me and I'll take a look?

I've just released a version which has a small fix to improve the handling of `id` for areas but that shouldn't affect you not seeing your zones.

**Comment by mrwee** [comment]
Very strange... I just noticed that I cannot use '1' as area reference. The editor returns an error. Is that change deliberate? 
A side note: When editing the configuration (e.g. 'port') the editor adds 'null', after 'port: ', if I edit it, it changes to 'n' or jumps to the top of the config... Maybe just a Firefox issue?

**Comment by dchesterton** [comment]
If you update to the latest version of the app you should be able to use '1' as the area reference. There was a small regression which has been fixed now.

The jumping about thing I've experienced too, it seems to be a bug with HA.

**Comment by mrwee** [comment]
Indeed it now accepts '1' :). Unfortunately it still doesn't work, and the log includes:
```
2021-02-11 22:46:59 - INFO: Starting texecom2mqtt v1.0.20...
2021-02-11 22:46:59 - INFO: Connected to alarm, sleeping for 0.5 seconds...
2021-02-11 22:47:00 - INFO: Connection ready
2021-02-11 22:47:00 - DEBUG: Executing serial number command
2021-02-11 22:47:00 - DEBUG: Received data chunk of length 11
2021-02-11 22:47:00 - INFO: Fetched serial number: 1167782031181
2021-02-11 22:47:00 - INFO: Logging in
2021-02-11 22:47:00 - DEBUG: Executing command 1
2021-02-11 22:47:00 - DEBUG: Received data chunk of length 5
/snapshot/app/dist/texecom/texecom.js:80
            throw new Error(`Unexpected start, expected 't', got ${headerStart}`);
            ^
Error: Unexpected start, expected 't', got A
    at Texecom.parseBuffer (/snapshot/app/dist/texecom/texecom.js:80:19)
    at Socket.<anonymous> (/snapshot/app/dist/texecom/texecom.js:246:26)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)
```

Config is now:
```
texecom:
  host: 192.168.1.xx
  udl_password: 'xxxx'
mqtt:
  host: 'mqtt://fqdn:1883'
  username: USERNAME
  password: PASSWORD
  client_id: texecom2mqtt
  keepalive: 5
  retain: true
homeassistant:
  discovery: true
areas:
  - id: '1'
    full_arm: armed_away
    part_arm_1: armed_home
zones: []
log: debug
```

**Comment by dchesterton** [comment]
Can you try it again and see if you get past that error? That error occurs occasionally when trying to connect. The panels seem to send corrupt data sometimes.

**Comment by dchesterton** [comment]
Did you get this working in the end?

**Comment by mrwee** [comment]
Unfortunately not :(

Something isn't quite right on my setup. I noticed that I also had  the MQTT problem, removing the ':1883' solved it.

But I only see two zones on my broker, none of them are listed in the entiities list, and I noticed that the device "Configuration\Devices" is gone (I think I used to have a "Texecom Premier 168" device there.

Have tried uninstalling/installing texecom2mqtt, but it doesn't change anything :(

**Comment by mrwee** [comment]
Think I've found some things. I'm unsure how much result in this not working for me:

**1)** 
Some of my zone names contains special characters, changing one of them via Wintex, made the parsing continue past the zone.
The characters are shown as: "�" in the logfile (Think they actually differ, but are shown as this)
They were also shown strange before, but I don't know if they now break anything. The correct characters seen on the panel, is not shown in Hass (never did though).

**2**
I see a lot of 
`INFO: Fetched Zone 3:`
in the logfile, but I think with it hits one of the special, something breaks.

**3**
See some of these timeout's, don't know their meaning or impact:
```
2021-02-14 14:16:18 - DEBUG: Command 3 timed out (attempt 1, id: 96).
2021-02-14 14:16:24 - DEBUG: Command 3 timed out (attempt 1, id: 103).
2021-02-14 14:16:32 - DEBUG: Command 3 timed out (attempt 1, id: 118).
2021-02-14 14:16:36 - DEBUG: Command 3 timed out (attempt 1, id: 120).
2021-02-14 14:17:04 - DEBUG: Command 11 timed out (attempt 1, id: 175)
```

**4**
Despite a lot of zones being fetched, they are not published to MQTT. Out of ~50 programmed zones, only 9 are published to MQTT.

**Comment by mrwee** [comment]
Got it!
One of the special characters seemed to break it. I replaced all I could find, now the device and all entities are there :). Looks funny on the panel though :)

Could character translations, be a candidate for a future improvement?

**Comment by dchesterton** [comment]
Glad it's working 🙂 Yeah definitely, what were the characters you used which broke it?

**Comment by mrwee** [comment]
If you, when using a panel to program the zone text, continuously press "Area" then you get got special characters. I can only assume they differ, depending on which language version, the central has been flashed with:
LS1 (Language Set 1) English/French/Dutch/German
LS2 (Language Set 2) English/Spanish/Italian/Portugese
LS3 (Language Set 3) English/Russian/Czech/Slovakian
LS4 (Language Set 4) English/Sweedish/Danish/Norwegian/Finnish
LS5 (Language Set 5) English/Polish/Hungarian/Estonain/Slovenian
LS6 (Language Set 6) English/Chinese

I'm running LS04, and was using Nordic characters. I assume they're outside "normal" 1-127 ASCII, but don't know.

**Comment by dchesterton** [comment]
Thanks, that's really helpful.

I've done a bit of investigation with those characters and it seems that there's a bug with the Texecom API where the alarm only ever sends a character as 1 byte. So characters which are 2 bytes or more - such as Nordic characters - get malformed.

I've pushed a change to handle the malformed characters better and still generate a valid topic name so it won't break the app anymore. Although it's not ideal, you can then 'restore' the name using your config if you wanted the correct name in Home Assistant, e.g.:

```
zones:
  - id: 1
    name: Zone å
```

**Comment by mrwee** [comment]
@dchesterton Thank you for your relentless efforts! 

It seems like it works like a charm. Somehow this 'bug' has interfered my setup since day 1. It wasn't until today I understood the implications :).

I'll test for a couple of days and get back with status :)

**Comment by dchesterton** [comment]
Hi @mrwee, how did you get on with the fix in the end?

**Comment by mrwee** [comment]
Hey @dchesterton. I do belive it's working now. have been testing different settings/changes without issues. Nordic characters still appear with ?, but it doesn't seem to crash anything :)

Again, much appreciate your fast reaction to the recent issues!

**Comment by mrwee** [comment]
Unfortunately I'm still suffering from this, with version 1.0.42
It simply stops updating the zones and only publishes power info :(.

`2021-06-24 20:13:21 - DEBUG: Updating system power...
2021-06-24 20:13:22 - DEBUG: Publishing to texecom2mqtt/power: {"battery_charging_current":18,"battery_voltage":13.56,"panel_current":918,"panel_voltage":13.63}
2021-06-24 20:14:12 - DEBUG: Updating system power...
2021-06-24 20:14:12 - DEBUG: Publishing to texecom2mqtt/power: {"battery_charging_current":18,"battery_voltage":13.56,"panel_current":747,"panel_voltage":13.63}`

**Comment by no1knows** [comment]
+1 (think this is a duplicate of https://github.com/dchesterton/texecom2mqtt-hassio/issues/22)

**Comment by dchesterton** [comment]
I've managed to get to the bottom of this bug and it has _finally_ been fixed in v1.2.0. Closing this.
