### ISSUE TITLE
2021-02-13 19:33:57 - ERROR: Unhandled rejection - Error: getaddrinfo ENOTFOUND core-mosquitto:1883

### ISSUE THREAD

**Issue by garethp85** [dchesterton/texecom2mqtt-hassio#14]
Hi, I am getting the following error which I am unable to fix. 

2021-02-13 19:33:57 - ERROR: Unhandled rejection - Error: getaddrinfo ENOTFOUND core-mosquitto:1883

**Comment by dchesterton** [comment]
Change your config from `host: core-mosquitto:1883` to simply `host: core-mosquitto` and it should fix the issue.

**Comment by garethp85** [comment]
That has fixed it. Thank you and thanks for replying so quickly. Really appreciate your work on this.

**Comment by plimps06** [comment]
I'm having the same problem but deleting the port number did not fix the problem.
